In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from astropy.table import Table
from sklearn.tree import DecisionTreeClassifier
import random
from sklearn import tree

In [2]:
#generate fake data
#create 5 empty lists (4 for features and 1 for labels)
#start a for loop that cycles through the range (0, 100)
#generate ranfom data to an empty list
#end for loop
#print the final lengths

In [20]:
#features
temps=[]
spec_type=[]
luminosity=[]
mass=[]
#label
ages=[]
for i in range(0,100):
    temp_ran=random.randint(3500, 60000)
    spec_ran=random.randint(0,7)
    lum_ran=random.randint(1, 1000000)
    mass_ran=random.randint(1, 100)
    ages_ran=random.randint(100000, 13000000)
    finaltemp=temps.append(temp_ran)
    finalspec=spec_type.append(spec_ran)
    finallum=luminosity.append(lum_ran)
    finalmass=mass.append(mass_ran)
    finalages=ages.append(ages_ran)
print(len(temps), len(spec_type),len(luminosity),len(mass),len(ages))

100 100 100 100 100

In [31]:
data={'temps':temps, 'spec_type':spec_type,
                  'luminosity':luminosity, 'mass': mass}

In [38]:
df = pd.DataFrame(data=data)
df

    temps  spec_type  luminosity  mass
0   29724          1      919319    35
1   31407          0      847455    15
2   40975          0      647111    79
3   10282          2      737333    62
4   59705          3      894293    29
5   39302          5      814399    90
6   31571          0      566834    20
7   26212          2      182421    73
8    5299          0      891238    37
9   40461          2      374272    26
10  29637          3      283602    98
11  21589          6       29281    13
12  55826          2      426041    51
13  49572          0      694399    64
14  10487          0      684494    10
15  12504          0      137236    75
16  50184          1      378894    16
17  41608          5      140969    76
18  56794          2      183392    84
19  50600          5       18374    66
20   5191          3      848122    48
21   5484          2      127638    69
22  54376          5      581521    88
23  32382          4      248148    61
24   7194          0      576566    75
25  36228          5       37248    30
26  45730          5      919554    14
27  15847          7      355041    19
28   8208          1      774153    69
29  57245          7      510219    78
..    ...        ...         ...   ...
70  39550          7      401968    36
71  45840          0      922306    26
72   6719          2      875078    22
73  10331          6       26913    27
74  35824          3      453533     6
75  51151          0      912246    95
76  59463          0      147831    96
77  25774          0      416839    26
78  50376          4      371534    99
79  54217          2      504104     4
80  31201          3      562768    92
81  11472          3      865752    18
82   8269          3       19594    35
83  12785          3      459662    33
84  21584          5      914254    71
85  44098          5      243595    25
86  20426          5      706058     4
87  34663          3      744614    64
88  27802          3       61398     2
89  42574          4      478106    41
90  34704          7      983419    64
91   6371          7       40869    52
92  13337          2      717591    92
93  57743          4      978188    98
94  23170          6      837739    24
95  59378          5      931808    63
96  40074          0      188978    89
97   9182          4      658064    45
98   3933          1      793487    48
99  34104          3      439699    27

[100 rows x 4 columns]

In [39]:
data_table = Table([temps,spec_type,luminosity,mass],names=('temps','spec_type','luminosity','mass'))

In [42]:
random.seed(2)
indices=[]
for i in range(0,10):
    indices.append(random.randint(0,100))
data_subset=[]
labels_subset=[]
for i in indices:
    print(i)
    data_subset.append(data_table[i])
    labels_subset.append(data_table[i])

7
11
10
46
21
94
85
39
32
77

In [49]:
random.seed(5)
indices=[]
for i in range(0,10):
    indices.append(random.randint(0,100))
data_subset=[]
labels_subset=[]
for i in indices:
    print(i)
    data_subset.append(data_table[i])
    labels_subset.append(data_table[i])

79
32
94
45
88
94
83
67
3
59

In [50]:
model = DecisionTreeClassifier()
subset_tree_fit=model.fit(data_subset,labels_subset)

In [51]:
plt.figure(figsize=(20,15))
tree.plot_tree(subset_tree_fit)

AttributeError: module 'sklearn.tree' has no attribute 'plot_tree'

In [58]:
random.seed(9)
indices=[]
for i in range(0,10):
    indices.append(random.randint(0,100))
data_subset=[]
labels_subset=[]
for i in indices:
    print(i)
    data_subset.append(data_table[i])
    labels_subset.append(data_table[i])

59
78
47
34
17
23
86
0
43
64

In [53]:
model = DecisionTreeClassifier()
subset_tree_fit=model.fit(data_subset,labels_subset)

In [54]:
plt.figure(figsize=(20,15))
tree.plot_tree(subset_tree_fit)

AttributeError: module 'sklearn.tree' has no attribute 'plot_tree'