In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("sunspots_data2.csv")
data

       Unnamed: 0  year  month  day  linear_year  daily_sunspots
0               0  1818      1    2     1818.004              -1
1               1  1818      1    3     1818.007              -1
2               2  1818      1    4     1818.010              -1
3               3  1818      1    5     1818.012              -1
4               4  1818      1    6     1818.015              -1
5               5  1818      1    7     1818.018              -1
6               6  1818      1    8     1818.021              65
7               7  1818      1    9     1818.023              -1
8               8  1818      1   10     1818.026              -1
9               9  1818      1   11     1818.029              -1
10             10  1818      1   12     1818.032              -1
11             11  1818      1   13     1818.034              37
12             12  1818      1   14     1818.037              -1
13             13  1818      1   15     1818.040              -1
14             14  1818      1   16     1818.042              -1
15             15  1818      1   17     1818.045              77
16             16  1818      1   18     1818.048              98
17             17  1818      1   19     1818.051             105
18             18  1818      1   20     1818.053              -1
19             19  1818      1   21     1818.056              -1
20             20  1818      1   22     1818.059              -1
21             21  1818      1   23     1818.062              -1
22             22  1818      1   24     1818.064              -1
23             23  1818      1   25     1818.067              25
24             24  1818      1   26     1818.070              -1
25             25  1818      1   27     1818.073              -1
26             26  1818      1   28     1818.075              38
27             27  1818      1   29     1818.078              20
28             28  1818      1   30     1818.081              -1
29             29  1818      1   31     1818.084              -1
...           ...   ...    ...  ...          ...             ...
73626       73626  2019      8    2     2019.585               0
73627       73627  2019      8    3     2019.588               0
73628       73628  2019      8    4     2019.590               0
73629       73629  2019      8    5     2019.593              12
73630       73630  2019      8    6     2019.596               0
73631       73631  2019      8    7     2019.599              11
73632       73632  2019      8    8     2019.601               0
73633       73633  2019      8    9     2019.604               0
73634       73634  2019      8   10     2019.607               0
73635       73635  2019      8   11     2019.610               0
73636       73636  2019      8   12     2019.612               0
73637       73637  2019      8   13     2019.615               0
73638       73638  2019      8   14     2019.618               0
73639       73639  2019      8   15     2019.621               0
73640       73640  2019      8   16     2019.623               0
73641       73641  2019      8   17     2019.626               0
73642       73642  2019      8   18     2019.629               0
73643       73643  2019      8   19     2019.632               0
73644       73644  2019      8   20     2019.634               0
73645       73645  2019      8   21     2019.637               0
73646       73646  2019      8   22     2019.640               0
73647       73647  2019      8   23     2019.642               0
73648       73648  2019      8   24     2019.645               0
73649       73649  2019      8   25     2019.648               0
73650       73650  2019      8   26     2019.651               0
73651       73651  2019      8   27     2019.653               0
73652       73652  2019      8   28     2019.656               0
73653       73653  2019      8   29     2019.659               0
73654       73654  2019      8   30     2019.662               0
73655       73655  2019      8   31     2019.664               0

[73656 rows x 6 columns]

In [3]:
years = data["year"]
daily_sun = data["daily_sunspots"]

In [ ]:
import matplotlib.pyplot as plt
plt.bar(years,daily_sun)#, width = 1)
plt.title("daily sunspots over time")
plt.ylabel("sunspots")
plt.show()